from os import path

__CURRENT_PROGRAM_LOCATION = f"{path.dirname(path.realpath(__file__))}".rstrip("mandel_imports").join("\\")
__IMAGE_FOLDER = f"{__CURRENT_PROGRAM_LOCATION}Images\\"
__IMAGE_IMPORT_FOLDER = f"{__CURRENT_PROGRAM_LOCATION}Imports\\Images_For_Importing\\"
__MANDEL_PPM_LOC = f"{__IMAGE_FOLDER}Mandelbrot PPMs\\"
__GRADIENT_PPM_LOC = f"{__IMAGE_FOLDER}Gradient PPMs\\"
RESOLUTION_STANDARD = (480, 288)
RESOLUTION_HALF = (240, 144)
RESOLUTION_QUARTER = (120, 72)
RESOLUTION_EIGHTH = (60, 36)
RESOLUTION_LIST = [RESOLUTION_STANDARD, RESOLUTION_HALF, RESOLUTION_QUARTER, RESOLUTION_EIGHTH]